import DocLayout from '../../components/DocLayout'
import CodeBlock from '../../components/CodeBlock'

const SectionHeading = ({ children }: { children: string }) => (
  <h2 style={{ fontSize: 18, fontWeight: 700, color: '#fff', letterSpacing: 0, margin: '2.5rem 0 1rem', paddingBottom: '0.5rem', borderBottom: '1px solid var(--border-contrast)' }}>
    {children}
  </h2>
)

const Step = ({ n, title, children }: { n: number; title: string; children: React.ReactNode }) => (
  <div style={{ display: 'grid', gridTemplateColumns: '28px 1fr', gap: '1rem', marginBottom: '2rem' }}>
    <div style={{
      width: 24, height: 24, borderRadius: '50%', background: '#ffffff',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      fontFamily: 'var(--font-mono)', fontSize: 11, color: '#000000', fontWeight: 800, marginTop: 2,
    }}>{n}</div>
    <div>
      <h3 style={{ fontSize: 15, fontWeight: 700, color: '#fff', margin: '2px 0 0.75rem' }}>{title}</h3>
      {children}
    </div>
  </div>
)

const BulletList = ({ items }: { items: string[] }) => (
  <ul style={{ color: 'var(--text-muted)', fontSize: 13, lineHeight: 1.8, paddingLeft: '1.2rem', margin: '0 0 1.5rem' }}>
    {items.map(item => <li key={item}>{item}</li>)}
  </ul>
)

export default function GettingStarted() {
  return (
    <DocLayout title="Getting Started">
      <p className="body-copy" style={{ marginBottom: '2rem' }}>
        SPM modernizes legacy pages without modifying the original server. The workflow is declarative:
        the theme describes selectors, <code>spm-cli</code> compiles a manifest, and the extension mounts isolated React components inside Shadow DOM.
      </p>

      <SectionHeading>What Each Part Does</SectionHeading>
      <BulletList items={[
        'site-package-manager: MV3 extension that loads manifests, applies global theme, extracts DOM data, and mounts components.',
        'spm-cli: C++17 compiler that transforms .vnr files into manifest.json and serves local hot-reload via WebSocket.',
        'spm-components: React component library used as the target for selector and reconstruct blocks.',
        'spm-websites: natural home for per-domain themes, CSS, and compiled manifests.',
        'spm-vscode: ergonomics layer providing syntax highlighting, linting, and autocomplete for Veneer Spec.',
      ]} />

      <SectionHeading>Mental Model</SectionHeading>
      <div style={{ display: 'grid', gap: 1, background: 'var(--border-contrast)', border: '1px solid var(--border-contrast)', borderRadius: 6, overflow: 'hidden', marginBottom: '2rem' }}>
        {[
          ['1', 'Inspect Legacy HTML', 'Identify containers, lists, links, forms, and metadata that already exist on the page.'],
          ['2', 'Write .vnr', 'Declare the target, the React component, and how each prop will be extracted.'],
          ['3', 'Compile manifest.json', 'spm-cli resolves classes, validates syntax, and emits the JSON consumed by the extension.'],
          ['4', 'Load in Browser', 'The extension fetches or receives the manifest, applies CSS, and renders components.'],
          ['5', 'Iterate with Hot-Reload', 'In dev mode, theme changes are recompiled and sent to the extension.'],
        ].map(([n, title, desc]) => (
          <div key={n} style={{ display: 'grid', gridTemplateColumns: '28px 1fr', gap: '1rem', background: 'var(--bg-surface)', padding: '1rem 1.25rem', alignItems: 'flex-start' }}>
            <div style={{
              width: 24, height: 24, borderRadius: '50%', background: '#ffffff',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              fontFamily: 'var(--font-mono)', fontSize: 11, color: '#000000', fontWeight: 800, marginTop: 2,
            }}>
              {n}
            </div>
            <div>
              <p style={{ color: '#fff', fontWeight: 700, fontSize: 14, margin: '0 0 0.25rem' }}>{title}</p>
              <p style={{ color: 'var(--text-muted)', fontSize: 13, lineHeight: 1.6, margin: 0 }}>{desc}</p>
            </div>
          </div>
        ))}
      </div>

      <SectionHeading>Running the Extension</SectionHeading>
      <Step n={1} title="Install Dependencies and Build">
        <p style={{ color: 'var(--text-muted)', fontSize: 13, lineHeight: 1.7, marginBottom: '0.75rem' }}>
          In the root of the extension repository, generate the <code>dist/</code> directory.
        </p>
        <CodeBlock>{`
npm install
npm run build
        `}</CodeBlock>
      </Step>

      <Step n={2} title="Load Extension in Chrome">
        <BulletList items={[
          'Open chrome://extensions.',
          'Enable Developer Mode.',
          'Click Load unpacked.',
          'Select the dist/ directory generated by the build.',
        ]} />
      </Step>

      <Step n={3} title="Prepare a Local Theme">
        <p style={{ color: 'var(--text-muted)', fontSize: 13, lineHeight: 1.7, marginBottom: '0.75rem' }}>
          A minimal theme requires <code>.vnr</code> files, optional CSS, and a compiled manifest.
          The CLI accepts directories and scans <code>.vnr</code> files recursively.
        </p>
        <CodeBlock>{`
theme/
  manifest.json
  content.css
  pages/
    gallery.vnr
  shared/
    classes.vnr
        `}</CodeBlock>
      </Step>

      <Step n={4} title="Compile or Watch Changes">
        <CodeBlock>{`
# compile a theme directory
spm compile theme/ -o theme/manifest.json

# start dev server
spm dev -d theme/
        `}</CodeBlock>
      </Step>

      <SectionHeading>Anti-flickering</SectionHeading>
      <p style={{ color: 'var(--text-muted)', fontSize: 13, lineHeight: 1.7, marginBottom: '1rem' }}>
        The extension prevents flashing the old page during reconstruction. The interceptor runs at <code>document_start</code>,
        temporarily hides the page body, and reveals rendering via <code>revealPage()</code> when the flow completes or aborts.
      </p>
      <BulletList items={[
        'Anti-flicker CSS kicks in before legacy content flashes on screen.',
        'The global theme applies CSS tokens and customStyles to the main document.',
        'React hosts use Shadow DOM to isolate component styles.',
        'Reconstructed containers are flagged to prevent duplicate mounting.',
      ]} />
    </DocLayout>
  )
}
